### ISSUE TITLE
Obsolete comment about TIOCLINUX

### ISSUE THREAD

**Issue by jwilk** [mmeeks/uxlaunch#1]
A comment in `xserver.c` reads:
> TIOCLINUX will tell us which console is currently showing for this purpose.

But the use TIOCLINUX was removed in 4105762411cb55fddefc596d44bdfe25cb6deed4.

**Comment by mmeeks** [comment]
Ah - so I think it is safe to say that I have only a very limited recollection of writing this code, or forking this module =)
I would assume that LXF are still maintaining this, and/or that you could get changes in there.

For my part - I'll close the ticket - here - since I've intention of pretending to maintain this.
If you fork it somewhere; and submit a push request to add some README.md that re-directs to you I'd be very happy to merge it.

Thanks for caring and contributing though ! =)
